class Prospector
  public

  def check_seed: (Integer seed) -> Integer # | FalseClass # false

  def gen_random_number: (Integer seed, Integer range) -> Integer?

  def location_count: () -> 1

  def mine: (Integer city) -> Integer

  def next_location: (Integer curr, Integer seed) -> Integer

  def set_ruby_chart: () -> void

  def show_results: (Integer p) -> 1

  private

  def initialize: (Array map, MapLocationFinder map_location_finder, Integer num_turns) -> void
end
